-- H2 compatible schema for tests
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS global_settings;
DROP TABLE IF EXISTS billing_records;
DROP TABLE IF EXISTS attentions;
DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS professional_profiles;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    rut VARCHAR(12) NOT NULL,
    phone VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'CLIENT',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_rut UNIQUE (rut)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    icon_key VARCHAR(100) NOT NULL,
    color_hex VARCHAR(7) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE professional_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    display_name VARCHAR(150) NOT NULL,
    business_name VARCHAR(150),
    specialty VARCHAR(100),
    description CLOB,
    address VARCHAR(255),
    city VARCHAR(100),
    country VARCHAR(100),
    default_session_duration_minutes INT NOT NULL DEFAULT 60,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uk_professional_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_pp_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_pp_cat FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_profile_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(10,2),
    duration_minutes INT,
    price_unit VARCHAR(50) NOT NULL DEFAULT 'SESSION',
    is_at_home BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_service_prof FOREIGN KEY (professional_profile_id) REFERENCES professional_profiles(id)
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    service_id BIGINT,
    reservation_start TIMESTAMP NOT NULL,
    reservation_end TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_res_cli FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_res_spec FOREIGN KEY (specialist_id) REFERENCES users(id),
    CONSTRAINT fk_res_serv FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(100) NOT NULL,
    performed_by VARCHAR(255) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    details VARCHAR(1000),
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE global_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL,
    config_value VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_settings_key UNIQUE (config_key)
);

CREATE TABLE attentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    duration_minutes INT,
    status VARCHAR(50) NOT NULL,
    observations VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_att_res FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_att_cli FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_att_spec FOREIGN KEY (specialist_id) REFERENCES users(id)
);

CREATE TABLE billing_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    attention_id BIGINT,
    client_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'CLP',
    payment_method VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    paid_at TIMESTAMP,
    external_reference VARCHAR(255),
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bill_res FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_bill_att FOREIGN KEY (attention_id) REFERENCES attentions(id),
    CONSTRAINT fk_bill_cli FOREIGN KEY (client_id) REFERENCES users(id),
    CONSTRAINT fk_bill_spec FOREIGN KEY (specialist_id) REFERENCES users(id)
);
