[versions]
kotlin = "2.0.21"
agp = "8.7.0"
compose-bom = "2024.12.01"
springboot = "3.3.1"
lifecycle = "2.8.7"
activity = "1.9.3"
navigation = "2.8.4"
room-runtime-android = "2.8.4"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "room-runtime-android" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.5" }
